### LOGIN : for Deepak
POST http://localhost:3000/login
Content-Type: application/json
{
    "username": "Deepak"
}

### GET POSTS : pass accessToken(from /login response) in Authorization header
GET http://localhost:4000/posts
Authorization: Bearer <accessToken>

### LOGIN : for Sharad
POST http://localhost:3000/login
Content-Type: application/json
{
    "username": "Sharad"
}

### GET POSTS : pass accessToken(from /login response) in Authorization header
GET http://localhost:4000/posts
Authorization: Bearer <accessToken>





### GET NEW TOKEN after accessToken expired: pass refreshToken(from /login response) as token below
## New token you can get from /login also, but that will generate multiple refreshTokens also and those don't have expiration date. so it's not secure to generate mutiple refresh tokens
POST http://localhost:3000/auth
Content-Type: application/json
{
    "token": "<refreshToken>"
}

### LOGOUT : pass refreshToken(from /login response) as token below
## This will delete the refreshToken from stored array.
DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token": "<refreshToken>"
}